### ISSUE TITLE
As a user I want the system to be moderated in a way, such that no one gets insulted by swear words or other inappropriate language.

### ISSUE THREAD

**Issue by awhoa** [sopra-fs22-group-18/server#2]
### Acceptance Criteria

- [x] The system automatically detects and deletes comments with swear words and inappropriate content.
- [x] The text moderation will work for comments in English. In order to cover non-English language comments, comments and posts will be able to get reported to an admin for manual correction. (see user stories 13 & 14).

### Development Tasks

- [x] sopra-fs22-group-18/server#133

- [x]  get textmoderation api, understand functionality, implement serverside
- [x] #187

**Comment by awhoa** [comment]
done

**Comment by melihcatal** [comment]
@awhoa Could you please reference your commit ?

**Comment by awhoa** [comment]
a4ba23b94751fa4b1b42990c4ac726e581959c22, a4ba23b94751fa4b1b42990c4ac726e581959c22, 5efa36c77089b9c99c5dc8fc9af03e921f827675, 1248aec3e94e8b6ce4343179d998d0c4c95e3275, socket: not me
